### ISSUE TITLE
Source code of ondd?

### ISSUE THREAD

**Issue by luckcolors** [Outernet-Project/orx86#4]
Hello.
I wasn't able to find the source code of the ondd decoder anywhere. Any reason why it's not avaible?
Thanks in advance.

**Comment by syedkarim** [comment]
Hi. The decoder is not open source.

**Comment by luckcolors** [comment]
I'm wondering are there any plans on making it opensource? it's the only component which isn't freely compilable.
Also this question should go in the FAQ in the forum.

**Comment by syedkarim** [comment]
Unfortunately, there are no plans to make ondd open source. Well, I take that back. Once we have our own satellites and bring our spectrum into use,, then we'll be open sourcing ondd.

**Comment by luckcolors** [comment]
Ok thanks for the info! I really like this project keep up the good work. :)
